name: code checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.x"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint checks (Ruff)
      run: |
        ruff check --output-format=github
    - name: Formatting checks (Ruff)
      run: |
        ruff format --diff
    - name: Import sort checks (isort)
      run: |
        isort --check --diff .
    - name: Formatting checks (Black)
      run: |
        black --check --diff .
    - name: Typing checks (mypy)
      run: |
        mypy .
